gradebook/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='gradebook'
urlpatterns = [
    path('', views.gradebook_menu, name='gradebook_menu'),
    path('select_evo/', views.gradebook_selection, name='gradebook_selection'),
    path('grade_evo_list/<int:cohort_id>/<int:evolution_id>', views.grade_evo_list, name='grade_evo_list'),
    path('grade_evo/<int:student_id>/<int:evolution_id>', views.grade_evo, name='grade_evo'),
    path('grade_evo/<int:student_id>/<int:evolution_id>/delete', views.grade_evo_delete, name='grade_evo_delete'),
    path('csv_dump', views.gradebook_csv_dump, name='gradebook_csv_dump'),
]

home/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "home"
urlpatterns = [
    path("", views.home_view, name="home_page"),
    path("unauthorized", views.unauthorized_view, name="unauthorized_view"),
    path("reset_password", views.reset_password, name="reset_password"),
]

rackandstack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rubric/", include("rubric.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("stucon/", include("stucon.urls")),
    path("gradebook/", include("gradebook.urls")),
    path("surveys/", include("surveys.urls")),
    path("", include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stucon/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "stucon"
urlpatterns = [
    path("", views.bulk_edit_list, name="student_list"),
    path("create", views.create_student_user, name="create_student_user"),
    path("<int:student_id>/edit", views.student_edit, name="student_edit"),
    path("<int:student_id>/", views.student_view, name="student_view"),
    path("<int:student_id>/delete", views.student_delete, name="student_delete"),
    path("bulk_create", views.bulk_create_students, name="bulk_create_students"),
    path("bulk_edit", views.bulk_edit_list, name="bulk_edit_list"),
    path("bulk_edit_results", views.bulk_edit_results, name="bulk_edit_results"),
    path(
        "bulk_status_update/<int:new_status>",
        views.bulk_status_update,
        name="bulk_status_update",
    ),
    path(
        "<int:student_id>/status_comment_view_checked",
        views.status_comment_view_checked,
        name="status_comment_view_checked",
    ),
    path(
        "<int:student_id>/status_comment_view_unchecked",
        views.status_comment_view_unchecked,
        name="status_comment_view_unchecked",
    ),
    path("csv_export", views.dump_csv_student_data, name="dump_student_data"),
    path("upload_image", views.upload_image, name="upload_image"),
    path(
        "<int:cohort>/student_directory",
        views.student_directory,
        name="student_directory",
    ),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

gradebook/models.py
from django.db import models
from django.contrib.auth.models import User

from stucon.models import Student

from rubric.models import Evolution, Trait
from django.core.exceptions import ValidationError

def is_objective(evo_pk):
    evolution = Evolution.objects.get(pk=evo_pk)
    if evolution.type == 'subj':
        raise ValidationError(f'{evolution} is not an objective evolution.')

# Create your models here.
class TraitScore(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,null=False, related_name='trait_student')
    trait = models.ForeignKey(Trait, on_delete=models.CASCADE, null=False)
    evolution = models.ForeignKey(Evolution, on_delete=models.CASCADE, null=False)
    trait_score = models.IntegerChoices('Trait Score', '0 1 2 3 4')
    score = models.PositiveIntegerField(null=False, choices=trait_score.choices)
    grader = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='trait_grader')
    comment = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        unique_together = ["student", "evolution", "trait", "grader"]

    def __str__(self):
        return f"{self.trait} - {self.score} - {self.student} - {self.evolution} - from: {self.grader}"

    def calculate_from_obj_score(self, obj_score):
        pass

class ObjectiveScore(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False, related_name='obj_student')
    evolution = models.ForeignKey(Evolution, on_delete=models.CASCADE, validators=[is_objective])
    score = models.PositiveIntegerField(null=False)
    grader = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='obj_grader')
    class Meta:
        unique_together = ["student", "evolution"]
    def __str__(self):
        return f"{self.evolution} - {self.score} - {self.student} - from: {self.grader}"
    
    def evolution_type(self):
        return self.evolution.type
    
    def get_time_as_str(self):
        return f"{str(self.score//60).zfill(2)}:{str(self.score%60).zfill(2)}"

gradebook/forms.py
from django import forms
from gradebook.models import ObjectiveScore, TraitScore
from rubric.models import ObjectiveEvolution, Evolution
from stucon.models import Cohort, Student
from django.forms import ModelForm, ModelChoiceField, CharField, IntegerField, ChoiceField, DurationField
from django.core.validators import MaxValueValidator, MinValueValidator 

class SelectEvolutionForm(forms.Form):
    cohort_choice = ModelChoiceField(Cohort.objects.all())
    evolution_choice = ModelChoiceField(Evolution.objects.all())

SCORE_CHOICES =(
    ("--", "--"),
    (0, "0"),
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
)

class TraitScoreForm(forms.Form):
    label = ''
    trait_score = ChoiceField(choices=SCORE_CHOICES)
    comment = CharField(max_length=200, required=False)

class ObjectiveScoreForm(forms.Form):
    label = ''
    score = IntegerField(min_value=0)

class TimeScoreForm(forms.Form):
    score = DurationField(label="Time")

gradebook/views.py
from django.shortcuts import get_object_or_404, render
from django.template.response import TemplateResponse
from django.http.response import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import user_passes_test
from django.forms import formset_factory
import csv

from django.urls import reverse
from datetime import datetime, timedelta

from django.contrib import messages

from stucon.models import Cohort, Student
from rubric.models import Evolution, ObjectiveEvolution, Trait

from .forms import (
    SelectEvolutionForm,
    TimeScoreForm,
    TraitScoreForm,
    ObjectiveScoreForm,
)
from .models import ObjectiveScore, TraitScore


def grader_check(user):
    return user.groups.filter(name="grader").exists()

def course_admin_check(user):
    return user.groups.filter(name="course_admin").exists()


# Create your views here.
@user_passes_test(grader_check)
def gradebook_menu(request):
    return TemplateResponse(request, "gradebook/gradebook_menu.html", {})

@user_passes_test(course_admin_check)
def gradebook_csv_dump(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="gradebook_data.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(['candidate_number','student','grader','evolution','trait','score', 'comment'])
    traitscores = TraitScore.objects.all()
    for tscore in traitscores:
        writer.writerow([str(tscore.student.candidate_number),str(tscore.student), str(tscore.grader.username), str(tscore.evolution), str(tscore.trait), str(tscore.score), str(tscore.comment)])

    objective_scores = ObjectiveScore.objects.all()
    for oscore in objective_scores:
        writer.writerow([str(oscore.student.candidate_number),str(oscore.student), str(oscore.grader.username), str(oscore.evolution), str(oscore.evolution.traits.all()), str(oscore.score), 'null'])

    return response

@user_passes_test(grader_check)
def grade_evo_list(request, cohort_id, evolution_id):
    students = Student.objects.filter(cohort=cohort_id, status="act").order_by(
        "user_id__last_name"
    )
    cohort = get_object_or_404(Cohort.objects.all(), pk=cohort_id)
    evo = get_object_or_404(Evolution.objects.all(), pk=evolution_id)
    if evo.type != "subj":
        scores = ObjectiveScore.objects.all().filter(evolution=evo)
    else:
        scores = TraitScore.objects.all().filter(grader=request.user, evolution=evo)
    return TemplateResponse(
        request,
        "gradebook/grade_evo_list.html",
        {
            "students": students,
            "evolution": evo,
            "cohort": cohort,
            "scores": scores,
        },
    )


@user_passes_test(grader_check)
def grade_evo(request, student_id, evolution_id):
    evo = get_object_or_404(Evolution, pk=evolution_id)
    stu = get_object_or_404(Student, pk=student_id)
    TraitScoreFormSet = formset_factory(TraitScoreForm, extra=0)
    # HANDLE GET REQUESTS
    if request.method == "GET":
        forms = []
        if evo.type == "subj":
            # Check if the student already has a grade from this user for this evolution.
            data = []
            trait_list = []
            for trait in evo.traits.all():
                if TraitScore.objects.filter(
                    trait=trait,
                    student=student_id,
                    grader=request.user,
                    evolution=evolution_id,
                ).exists():
                    ts = TraitScore.objects.get(
                        trait=trait,
                        student=student_id,
                        grader=request.user,
                        evolution=evolution_id,
                    )
                    data.append(
                        {
                            "trait_score": ts.score,
                            "comment": ts.comment,
                        }
                    )
                else:
                    data.append({"trait_score": "--"})
                trait_list.append(str(trait))

            fs = TraitScoreFormSet(initial=data)
            data = zip(fs, trait_list)
            return TemplateResponse(
                request,
                "gradebook/grade_subj_evo.html",
                {
                    "data": data,
                    "formset": fs,
                    "evolution": evo,
                    "student": stu,
                },
            )

        elif evo.type == "count":
            if ObjectiveScore.objects.filter(
                evolution=evolution_id, student=student_id
            ).exists():
                objscore = ObjectiveScore.objects.get(
                    evolution=evolution_id, student=student_id
                )
                obj_score_form = ObjectiveScoreForm(initial={"score": objscore.score})
            else:
                obj_score_form = ObjectiveScoreForm()
            forms.append(obj_score_form)

        elif evo.type == "time":
            if ObjectiveScore.objects.filter(
                evolution=evolution_id, student=student_id
            ).exists():
                objscore = ObjectiveScore.objects.get(
                    evolution=evolution_id, student=student_id
                )
                time_score_form = TimeScoreForm(
                    initial={"score": timedelta(seconds=objscore.score)}
                )
            else:
                time_score_form = TimeScoreForm(initial={"score": timedelta()})
            forms.append(time_score_form)

        return TemplateResponse(
            request,
            "gradebook/grade_obj_evo.html",
            {
                "forms": forms,
                "evolution": evo,
                "student": stu,
            },
        )
    if request.method == "POST":
        if evo.type == "subj":
            data = request.POST

            fs = TraitScoreFormSet(request.POST, request.FILES)
            if fs.is_valid():
                for form, trait in zip(fs, evo.traits.all()):
                    if form.cleaned_data["trait_score"] == "--":
                        continue
                    if TraitScore.objects.filter(
                        trait=trait,
                        student=student_id,
                        grader=request.user,
                        evolution=evolution_id,
                    ).exists():
                        ts = TraitScore.objects.get(
                            trait=trait,
                            student=student_id,
                            grader=request.user,
                            evolution=evolution_id,
                        )
                        ts.score = form.cleaned_data["trait_score"]
                        ts.comment = form.cleaned_data["comment"]
                    else:
                        ts = TraitScore(
                            trait=trait,
                            student=stu,
                            evolution=evo,
                            grader=request.user,
                            score=form.cleaned_data["trait_score"],
                            comment=form.cleaned_data["comment"],
                        )
                    ts.save()
        elif evo.type == "count":
            if ObjectiveScore.objects.filter(
                student=student_id, evolution=evolution_id
            ).exists():
                os = ObjectiveScore.objects.get(
                    student=student_id, evolution=evolution_id
                )
                os.score = request.POST.get("score")
                os.grader = request.user
            else:
                os = ObjectiveScore(
                    score=request.POST.get("score"),
                    grader=request.user,
                    evolution=evo,
                    student=stu,
                )
            os.save()
        elif evo.type == "time":
            if request.POST.get("score") != "":
                try:
                    time = datetime.strptime(request.POST.get("score"), "%H:%M:%S")
                except:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        "Invalid input: Time should be formatted HH:MM:SS.",
                    )
                    return HttpResponseRedirect(
                        reverse(
                            "gradebook:grade_evo_list",
                            kwargs={
                                "cohort_id": stu.cohort.id,
                                "evolution_id": evolution_id,
                            },
                        )
                    )
                delta = timedelta(
                    hours=time.hour, minutes=time.minute, seconds=time.second
                )
            if ObjectiveScore.objects.filter(
                student=student_id, evolution=evolution_id
            ).exists():
                os = ObjectiveScore.objects.get(
                    student=student_id, evolution=evolution_id
                )
                os.score = delta.total_seconds()
                os.grader = request.user
            else:
                os = ObjectiveScore(
                    grader=request.user,
                    evolution=evo,
                    student=stu,
                    score=delta.total_seconds(),
                )
            os.save()
    messages.add_message(
        request, messages.SUCCESS, f"Successfully graded {evo} for {stu}."
    )
    return HttpResponseRedirect(
        reverse(
            "gradebook:grade_evo_list",
            kwargs={"cohort_id": stu.cohort.id, "evolution_id": evolution_id},
        )
    )


@user_passes_test(grader_check)
def gradebook_selection(request):
    cohort_id = request.GET.get("cohort_choice")
    evolution_id = request.GET.get("evolution_choice")
    form = SelectEvolutionForm()
    if cohort_id and evolution_id:
        return HttpResponseRedirect(
            reverse(

gradebook/templates/gradebook/grade_evo_delete.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
<h1>Delete Score</h1>

<p>Are you sure you want to delete the {{ evolution.name }} score(s) for: {{ student.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-outline-danger" type="submit" value="Yes, delete.">
</form>
{% endblock %}

gradebook/templates/gradebook/grade_evo_list.html
{% extends "base_bootstrap_nav.html" %}

{% block content %}
<h1>Grading {{ evolution }} - {{ cohort }}</h1>
<p>
    <a class="btn btn-outline-primary" target="_blank" href="{% url 'stucon:student_directory' cohort.pk %}">Student Picture Directory</a>
</p>
<p>
    <table class="table table-hover" id="grades">
        {% if evolution.type == 'subj' %}
            <!-- Subjective Evolution Gradesheet -->
            <tr class="text-center">
                <th class="text-start"><h3> Student </h3></th>
                {% for trait in evolution.traits.all %}
                <th>
                    <h3>{{ trait }}</h3>
                </th>
                {% endfor %}
            </tr>
            {% for student in students %}
            <tr>
                <td><a href="{% url 'stucon:student_view' student.id %}">{{ student }}</a></td>
                {% for trait in evolution.traits.all %}
                    <td>
                        {% for score in scores %}
                            {% if score.trait.id == trait.id and score.student.id == student.id %}
                                <div class="text-center"><h5>{{ score.score }}</h5></div> {% if score.comment %}<div class="text-center"><em><small class="text-muted">{{ score.comment }}</small></em> </div>{% endif %}
                            {% endif %}
                        {% endfor %}
                    </td>
                {% endfor %}
                <td>
                    <small>
                        <a href="{% url 'gradebook:grade_evo' student.id evolution.id %}">Edit</a> | 
                        <a href="{% url 'gradebook:grade_evo_delete' student.id evolution.id %}">Delete</a>
                    </small>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <!-- Objective Evolution Gradelist -->
            <tr>
                <th> Student </th>
                <th>
                    {% if evolution.type == 'time' %}Time
                    {% elif evolution.type == 'count' %}Count
                    {% else %} Pass/Fail {% endif %}
                </th>
                <th>Actions</th>
            </tr>
            {% for student in students %}
            <tr>
                <td><a href="{% url 'stucon:student_view' student.id %}">{{ student }}</a></td>
                <td>
                    {% for score in scores %}
                        {% if score.student.id == student.id %}
                            {% if evolution.type == 'time' %}
                                {{ score.get_time_as_str }}
                            {% else %}
                                {{ score.score }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <small>
                    <a href="{% url 'gradebook:grade_evo' student.id evolution.id %}">Edit</a> | 
                    <a href="{% url 'gradebook:grade_evo_delete' student.id evolution.id %}">Delete</a>
                    </small>
                </td>
            </tr>
            {% endfor %}
        {% endif %}
    </table>
</p>
            
{% endblock %}

gradebook/templates/gradebook/grade_obj_evo.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
{% load crispy_forms_tags %}
<h1>Grading {{ evolution }} for {{ student }}</h1>
<p>
    <form action="" method="post">
      {% csrf_token %}
      {% for form in forms %}
      <div>
        <b>{{form.label}}</b>
        {{ form|crispy }}
      </div>
    </br>
      {% endfor %}
      <input class="btn btn-outline-primary" type="submit" value="Submit">
      <input class="btn btn-outline-danger" type="submit" value="Cancel" onclick="window.location.href='{% url 'gradebook:grade_evo_list' student.cohort.id evolution.id %}';return false;">
    </form>
  </p>

{% endblock %}

gradebook/templates/gradebook/grade_subj_evo.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
{% load crispy_forms_tags %}
<h1>Grading {{ evolution }} for {{ student }}</h1>
<p>
    <form action="" method="post">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form, trait in data %}
      <div class="border border-3 border-primary rounded-3 p-3 m-3 ">
        <b>{{trait}}</b>
        {{ form|crispy }}
      </div>
    </br>
      {% endfor %}
      <input class="btn btn-outline-primary" type="submit" value="Submit">
      <input class="btn btn-outline-danger" type="submit" value="Cancel" onclick="window.location.href='{% url 'gradebook:grade_evo_list' student.cohort.id evolution.id %}';return false;">
    </form>
  </p>

{% endblock %}

gradebook/templates/gradebook/gradebook_menu.html
{% extends "base_bootstrap_nav.html" %}

{% block content %}

<h1>Gradebook</h1>

<h2>Select an action:</h2>

<ul>
    <li>
        <a href="{% url 'gradebook:gradebook_selection' %}">Grade an Evolution</a>
    </li>
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'gradebook:gradebook_csv_dump' %}">Export Grades as CSV</a>
    </li>
    {% endif %}
</ul>



{% endblock %}

gradebook/templates/gradebook/gradebook_selection.html
{% extends "base_bootstrap_nav.html" %}

{% block content %}
{% load crispy_forms_tags %}

<h1>Choose an Evolution</h1>

<h2>Select an evolution to grade:</h2>

<p>
    <form action="" method="get">
      {% csrf_token %}
      {{ form|crispy }}
    </br>
      <input class="btn btn-outline-primary" type="submit" value="Submit">
      <input class="btn btn-outline-danger" type="submit" value="Cancel" onclick="window.location.href='{% url 'gradebook:gradebook_menu' %}';return false;">
    </form>
  </p>



{% endblock %}