home/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "home"
urlpatterns = [
    path("", views.home_view, name="home_page"),
    path("unauthorized", views.unauthorized_view, name="unauthorized_view"),
    path("reset_password", views.reset_password, name="reset_password"),
]

rackandstack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rubric/", include("rubric.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("stucon/", include("stucon.urls")),
    path("gradebook/", include("gradebook.urls")),
    path("surveys/", include("surveys.urls")),
    path("", include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stucon/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "stucon"
urlpatterns = [
    path("", views.bulk_edit_list, name="student_list"),
    path("create", views.create_student_user, name="create_student_user"),
    path("<int:student_id>/edit", views.student_edit, name="student_edit"),
    path("<int:student_id>/", views.student_view, name="student_view"),
    path("<int:student_id>/delete", views.student_delete, name="student_delete"),
    path("bulk_create", views.bulk_create_students, name="bulk_create_students"),
    path("bulk_edit", views.bulk_edit_list, name="bulk_edit_list"),
    path("bulk_edit_results", views.bulk_edit_results, name="bulk_edit_results"),
    path(
        "bulk_status_update/<int:new_status>",
        views.bulk_status_update,
        name="bulk_status_update",
    ),
    path(
        "<int:student_id>/status_comment_view_checked",
        views.status_comment_view_checked,
        name="status_comment_view_checked",
    ),
    path(
        "<int:student_id>/status_comment_view_unchecked",
        views.status_comment_view_unchecked,
        name="status_comment_view_unchecked",
    ),
    path("csv_export", views.dump_csv_student_data, name="dump_student_data"),
    path("upload_image", views.upload_image, name="upload_image"),
    path(
        "<int:cohort>/student_directory",
        views.student_directory,
        name="student_directory",
    ),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

surveys/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'surveys'
urlpatterns = [
    path('', views.survey_list, name='survey_list'),
    path('create', views.survey_create, name='survey_create'),
    path('<int:survey_id>/edit', views.survey_edit, name='survey_edit'),
    path('<int:survey_id>/', views.survey_view, name='survey_view'),
    path('<int:survey_id>/delete', views.survey_delete, name='survey_delete'),
    path('take/<int:survey_id>', views.survey_take_menu, name='survey_take'),
    path('take/<int:survey_id>/nominations',
         views.survey_take_nominations, name='survey_take_nominations'),
    path('take/<int:survey_id>/perceptions',
         views.survey_take_perceptions, name='survey_take_perceptions'),
    path('take/<int:survey_id>/peerfeedback',
         views.survey_take_pf, name='survey_take_pf'),
    path('take/<int:survey_id>/questions',
         views.survey_take_qa, name='survey_take_qa'),
    path('take/<int:survey_id>/topbot5',
         views.survey_take_topbot5, name='survey_take_topbot5'),
    path('review', views.survey_review_menu, name='survey_review_menu'),
    path('review/nominations', views.survey_review_nominations,
         name='survey_review_nominations'),
    path('review/nom/search', views.nom_search_view, name='nom_search_view'),
    path('review/qa/search', views.qa_search_view, name='qa_search_view'),
    path('review/topbot5/search', views.topbot5_search_view,
         name='topbot5_search_view'),
    path('review/questions', views.survey_review_questions,
         name='survey_review_questions'),
    path('review/topbot5', views.survey_review_topbot5,
         name='survey_review_topbot5'),
    path('export/survey_question_responses', views.dump_csv_survey_question_data,
         name='export_survey_question_responses'),
    path('export/survey_nomination_responses', views.dump_csv_survey_nomination_data,
         name='export_survey_nomination_responses'),
    path('export/survey_topbot5_responses', views.dump_csv_survey_topbot5_data,
         name='export_survey_topbot5_responses'),
    path('export/survey_pf_responses', views.dump_csv_survey_pf_data,
         name='export_survey_pf_responses'),
    path('export/survey_perception_responses', views.dump_csv_survey_perception_data,
         name='export_survey_perception_responses'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

surveys/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import (
    BottomFiveResponse,
    NominationResponse,
    PeerFeedbackResponse,
    PerceptionResponse,
    Survey,
    SurveyQuestionResponse,
    TopFiveResponse,
)


class SurveyForm(ModelForm):
    class Meta:
        model = Survey
        fields = [
            "name",
            "survey_qs",
            "nomination_qs",
            "perception_qs",
            "peer_feedback",
            "topbot5",
            "scope",
            "active",
        ]
        labels = {
            "survey_qs": "Survey Questions",
            "nomination_qs": "Nomination Questions",
            "perception_qs": "Perception Questions",
            "topbot5": "Top/Bottom 5",
        }


# https://stackoverflow.com/a/291968
# How to filter the options on a ModelForm object - for example, we don't want to see all students
# in this dropdown, we just want the students who are in the same cohort.
class TopFiveResponseForm(ModelForm):
    class Meta:
        model = TopFiveResponse
        fields = ["top_five_select"]
        labels = {
            "top_five_select": "Top 5 Candidate",
        }


class BottomFiveResponseForm(ModelForm):
    class Meta:
        model = BottomFiveResponse
        fields = ["bottom_five_select"]
        labels = {
            "bottom_five_select": "Bottom 5 Candidate",
        }


class NominationResponseForm(ModelForm):
    class Meta:
        model = NominationResponse
        fields = ["subject", "comment", "question"]
        labels = {
            "subject": "Candidate",
            "comment": "Comment",
        }
        widgets = {"question": forms.HiddenInput()}


class PerceptionResponseForm(ModelForm):
    class Meta:
        model = PerceptionResponse
        fields = ["subject", "score", "question"]
        labels = {
            "score": "Score",
        }
        widgets = {
            "score": forms.RadioSelect(),
            "question": forms.HiddenInput(),
            "subject": forms.HiddenInput(),
        }


class SurveyQuestionResponseForm(ModelForm):
    class Meta:
        model = SurveyQuestionResponse
        fields = ["text", "question"]
        labels = {
            "text": "Answer",
        }
        widgets = {
            "question": forms.HiddenInput(),
        }


class PeerFeedbackResponseForm(ModelForm):
    class Meta:
        model = PeerFeedbackResponse
        fields = ["positive_feedback", "negative_feedback", "subject"]
        widgets = {
            "subject": forms.HiddenInput(),
        }

surveys/views.py
from django.shortcuts import render
from django.template.base import Template
from django.urls import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms import formset_factory
from operator import itemgetter


from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.models import User

import csv
import io
import copy

from stucon.models import Student
from .models import (
    Survey,
    NominationResponse,
    PeerFeedbackResponse,
    PerceptionResponse,
    TopFiveResponse,
    BottomFiveResponse,
    SurveyQuestionResponse,
    SurveyQuestion,
)
from .forms import (
    NominationResponseForm,
    SurveyForm,
    TopFiveResponseForm,
    BottomFiveResponseForm,
    PerceptionResponseForm,
    PeerFeedbackResponseForm,
    SurveyQuestionResponseForm,
)


def course_admin_check(user):
    return user.groups.filter(name="course_admin").exists()


def student_check(user):
    if Student.objects.filter(user_id=user.id).exists():
        stu = Student.objects.get(user_id=user.id)

    return user.groups.filter(name="student").exists() and stu.status == "act"


# Create your views here.
@login_required
def survey_list(request):
    if Student.objects.filter(user_id=request.user.id).exists():
        user_is_student = True
    else:
        user_is_student = False
    surveys = Survey.objects.all().order_by("name")
    paginator = Paginator(surveys, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return TemplateResponse(
        request,
        "surveys/survey_list.html",
        {
            "page_obj": page_obj,
            "user_is_student": user_is_student,
        },
    )


@user_passes_test(course_admin_check)
def survey_create(request):
    if request.method == "POST":
        survey_form = SurveyForm(request.POST)
        new_survey = survey_form.save()
        messages.add_message(
            request, messages.SUCCESS, f"Successfully created new survey: {new_survey}."
        )
        return HttpResponseRedirect(reverse("surveys:survey_list"))

    if request.method == "GET":
        survey_form = SurveyForm()
        return TemplateResponse(
            request,
            "surveys/survey_form.html",
            {
                "form": survey_form,
            },
        )


@user_passes_test(course_admin_check)
def survey_view(request, survey_id):
    survey = get_object_or_404(Survey.objects.all(), pk=survey_id)
    return TemplateResponse(request, "surveys/survey_view.html", {"survey": survey})


@user_passes_test(course_admin_check)
def survey_edit(request, survey_id):
    if request.method == "POST":
        survey = get_object_or_404(Survey.objects.all(), pk=survey_id)
        survey_form = SurveyForm(request.POST, instance=survey)
        survey_form.save()
        messages.add_message(
            request, messages.SUCCESS, f"Successfully updated {survey}."
        )
        return HttpResponseRedirect(reverse("surveys:survey_list"))

    if request.method == "GET":
        survey = get_object_or_404(Survey.objects.all(), pk=survey_id)
        edit_form = SurveyForm(instance=survey)
        return TemplateResponse(
            request,
            "surveys/survey_form.html",
            {
                "form": edit_form,
                "survey": survey,
            },
        )


@user_passes_test(course_admin_check)
def survey_delete(request, survey_id):
    if request.method == "POST":
        survey = Survey.objects.get(pk=survey_id)
        survey_name = survey.name
        # Delete the User object instead of the Student object - Cascade will delete the Student.
        survey.delete()
        messages.add_message(
            request, messages.SUCCESS, f"Successfully deleted {survey_name}."
        )
        return HttpResponseRedirect(reverse("surveys:survey_list"))
    else:
        survey = get_object_or_404(Survey.objects.all(), pk=survey_id)
        return TemplateResponse(
            request, "surveys/survey_delete.html", {"survey": survey}
        )


@user_passes_test(student_check)
def survey_take_menu(request, survey_id):
    stu = get_object_or_404(Student.objects.all(), user_id=request.user.id)
    if request.method == "GET":
        survey = get_object_or_404(Survey.objects.all(), pk=survey_id)
        if survey.active == False:
            messages.add_message(
                request,
                messages.ERROR,
                "The survey you are attempting to take is not active. Please select an active survey.",
            )
            return HttpResponseRedirect(reverse("surveys:survey_list"))
        survey_progress = survey.check_authored_responses_exist(
            request.user.id)

    return TemplateResponse(
        request,
        "surveys/survey_take_menu.html",
        {
            "survey": survey,
            "survey_progress": survey_progress,
            "cohort": stu.cohort,
        },
    )


@user_passes_test(student_check)
def survey_take_nominations(request, survey_id):
    survey = get_object_or_404(Survey.objects.all(), pk=survey_id)
    student_user = get_object_or_404(
        Student.objects.all(), user_id=request.user.id)
    nomination_forms = []
    questions = []
    NominationResponseFormset = formset_factory(
        NominationResponseForm, extra=0)

    if request.method == "POST":
        fs = NominationResponseFormset(request.POST, request.FILES)
        if fs.is_valid():
            for form in fs:
                if NominationResponse.objects.filter(
                    author=student_user,
                    question=form.cleaned_data["question"],
                    survey=survey,
                ).exists():
                    nom_response = NominationResponse.objects.get(
                        author=student_user,
                        question=form.cleaned_data["question"],
                        survey=survey,
                    )
                    nom_response.subject = form.cleaned_data["subject"]
                    nom_response.comment = form.cleaned_data["comment"]
                    nom_response.save()
                else:
                    nom_response = form.save(commit=False)
                    nom_response.author = Student.objects.get(
                        user_id=request.user.id)
                    nom_response.survey = Survey.objects.get(pk=survey_id)
                    nom_response.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Nominations saved.")
            return HttpResponseRedirect(
                reverse("surveys:survey_take", kwargs={"survey_id": survey_id})
            )
        else:
            for nomination_q in survey.nomination_qs.all().order_by("question_text"):
                questions.append(nomination_q)
            for form, question in zip(fs, questions):
                if survey.scope == "team":
                    form.fields["subject"].queryset = Student.objects.filter(
                        cohort=student_user.cohort, team=student_user.team, status="act"
                    ).exclude(pk=student_user.pk)
                if survey.scope == "cohort":
                    form.fields["subject"].queryset = Student.objects.filter(
                        cohort=student_user.cohort, status="act"
                    ).exclude(pk=student_user.pk)
                form.question_text = question
            return TemplateResponse(
                request,
                "surveys/survey_take_nominations.html",
                {
                    "survey": survey,
                    "formset": fs,
                },
            )

    for nomination_q in survey.nomination_qs.all().order_by("question_text"):
        questions.append(nomination_q)
        if NominationResponse.objects.filter(
            author=student_user, question=nomination_q, survey=survey
        ).exists():
            nom_resp = NominationResponse.objects.get(
                author=student_user, question=nomination_q, survey=survey
            )
            nomination_forms.append(
                {
                    "subject": nom_resp.subject,
                    "comment": nom_resp.comment,
                    "question": nomination_q,
                }
            )
        else:
            nomination_forms.append(
                {
                    "subject": None,
                    "comment": None,
                    "question": nomination_q,
                }
            )
    fs = NominationResponseFormset(initial=nomination_forms)
    for form, question in zip(fs, questions):
        if survey.scope == "team":
            form.fields["subject"].queryset = Student.objects.filter(
                cohort=student_user.cohort, team=student_user.team
            ).exclude(pk=student_user.pk)
        if survey.scope == "cohort":
            form.fields["subject"].queryset = Student.objects.filter(
                cohort=student_user.cohort
            ).exclude(pk=student_user.pk)
        form.question_text = question
    return TemplateResponse(
        request,
        "surveys/survey_take_nominations.html",
        {
            "survey": survey,
            "formset": fs,
        },
    )


@user_passes_test(student_check)
def survey_take_perceptions(request, survey_id):
    survey = get_object_or_404(Survey.objects.all(), pk=survey_id)
    student_user = get_object_or_404(
        Student.objects.all(), user_id=request.user.id)
    question_list = []
    teammate_list = []
    perception_forms = []
    PerceptionResponseFormset = formset_factory(
        PerceptionResponseForm, extra=0)

    if request.method == "POST":
        fs = PerceptionResponseFormset(request.POST, request.FILES)

surveys/templates/surveys/nom_search_results.html
<div id="searchresults">
    <table class="table table-hover p-3 m-3">
        <tr>
            <th>Student</th><th>Cohort</th><th>Source</th><th>Positive Nominations</th><th>Negative Nominations</th>
        </tr>
        {% for row in data %}
        <tr>
            <td><a href={% url 'stucon:student_view' row.student.id %}>{{ row.student }}</a></td>
            <td>{{ row.student.cohort }}</td>
            <td>{{ row.student.source }}</td>
            <td>{{ row.pos_noms }}</td>
            <td>{{ row.neg_noms }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

surveys/templates/surveys/qa_search_results.html
<div id="searchresults">
    {% for q in questions %}
    <div class="border border-3 rounded-3 p-3 m-3">
        <h3>{{ q.question }}</h3>
        <table class="table table-hover">
            <tr>
                <th>Student</th><th>Cohort</th><th>Source</th><th>Question Response</th>
            </tr>
            {% for response in q.responses.all %}
            <tr>
                <td><a href={% url 'stucon:student_view' response.author.id %}>{{ response.author }}</a></td>
                <td>{{ response.author.cohort }}</td>
                <td>{{ response.author.source }}</td>
                <td>{{ response.text }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endfor %}
</div>

surveys/templates/surveys/survey_delete.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
<h1>Delete Survey</h1>

<p>Are you sure you want to delete this survey: {{ survey }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-outline-danger" type="submit" value="Yes, delete.">
</form>
{% endblock %}

surveys/templates/surveys/survey_form.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% if survey %}
    <h1>Edit Survey</h1>
{% else %}
    <h1>Create Survey</h1>
{% endif %}
<p>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
    </br>
      <input class="btn btn-outline-primary" type="submit" value="Submit">
      <input class="btn btn-outline-warning" type="submit" value="Cancel" onclick="window.location.href='{% url 'surveys:survey_list' %}';return false;">
      {% if survey %}
      <input class="btn btn-outline-danger" type="submit" value="Delete" onclick="window.location.href='{% url 'surveys:survey_delete' survey.id %}'; return false;">
      {% endif %}
    </form>
  </p>

{% endblock %}

surveys/templates/surveys/survey_list.html
{% extends "base_bootstrap_nav_splash.html" %}

{% block content %}
    <h1>Surveys</h1>
    <p>
        {% if not user_is_student %}
            <a class="btn btn-outline-primary" href="{% url 'surveys:survey_create' %}">Create Survey</a>
            <a class="btn btn-outline-primary" href="{% url 'surveys:survey_review_menu' %}">Review Survey Responses</a>
        {% endif %}
    {% if page_obj %}
    <table class="table">
        <tr>
            <th>Survey Title</th><th>Scope</th> <th>Nominations</th><th>Perceptions</th><th>Peer Feedback</th><th>Q&A</th><th>Top 5 / Bottom 5</th> {% if not user_is_student %}<th>Active</th><th>Actions</th> {% endif %}
        </tr>
        {% for survey in page_obj.object_list %}
        {% if user_is_student and survey.active or not user_is_student %}
        <tr>
            {% if not user_is_student %}
            <td><a href="{% url 'surveys:survey_view' survey.id %}"> {{ survey.name }} </a></td>
            {% endif %}
            {% if user_is_student %}
            <td><a href="{% url 'surveys:survey_take' survey.id %}"> {{ survey.name }} </a></td>
            {% endif %}
            <td>{{ survey.scope }}</td>
            <td>{{ survey.nomination_qs.count }}</td>
            <td>{{ survey.perception_qs.count }}</td>
            <td>{{ survey.peer_feedback }}</td>
            <td>{{ survey.survey_qs.count }}</td>
            <td>{{ survey.topbot5 }}</td>
            {% if not user_is_student %}
            <td>{{ survey.active }}</td>
            <td>
                <a href="{% url 'surveys:survey_edit' survey.id %}"> Edit </a> | 
                <a href="{% url 'surveys:survey_delete' survey.id %}"> Delete </a>
            </td>
            {% endif %}
        </tr>
    {% endif %}
    {% endfor %}
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
    <p>There are no surveys in the database.</p>
    {% endif %}
    </p>

{% endblock %}

surveys/templates/surveys/survey_review_nominations.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
<h1> Nominations Review </h1>
<form 
hx-get="{% url 'surveys:nom_search_view' %}"
hx-target="#searchresults"
hx-swap="outerHTML"
hx-trigger="submit, input delay:0.3s, every 60s"
>
    <input type="text" class="form-control" name="search" placeholder="Filter..." value="{{ search }}">
    <input type="checkbox" id="negative-sort" name="negative-sort" value="negative-sort">
    <label for="negative-sort">Sort by Negative (blank will sort by Positives)</label><br>
</form>
<p>
    {% include 'surveys/nom_search_results.html' %}
</p>

{% endblock %}

surveys/templates/surveys/survey_review_questions.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
<h1> Q&A Review </h1>
<form 
hx-get="{% url 'surveys:qa_search_view' %}"
hx-target="#searchresults"
hx-swap="outerHTML"
hx-trigger="submit, input delay:0.3s, every 60s"
>
    <input type="text" class="form-control" name="search" placeholder="Filter..." value="{{ search }}">
</form>
<p>
    {% include 'surveys/qa_search_results.html' %}
</p>

{% endblock %}

surveys/templates/surveys/survey_review_topbot5.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
<h1> Top/Bottom 5 Review </h1>
<form 
hx-get="{% url 'surveys:topbot5_search_view' %}"
hx-target="#searchresults"
hx-swap="outerHTML"
hx-trigger="submit, input delay:0.3s, every 60s"
>
    <input type="text" class="form-control" name="search" placeholder="Filter..." value="{{ search }}">
</form>
<p>
    {% include 'surveys/topbot5_search_results.html' %}
</p>

{% endblock %}

surveys/templates/surveys/survey_take_nominations.html
{% extends "base_bootstrap_nav_splash.html" %}
{% block content %}
{% load crispy_forms_tags %}
<p>
  <h1>{{ survey }}: Nominations</h1>
</p>
<p>
    <form action="" method="post">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset %}
      <div class="border border-3 border-primary rounded-3 p-3 m-3">
      <h3> {{ form.question_text }} </h3>
        {{ form|crispy }}
      </div>
        {% endfor %}
      <div class= "p-3 m-3">
        <input class="btn btn-outline-primary" type="submit" value="Submit">
        <input class="btn btn-outline-warning" type="submit" value="Cancel" onclick="window.location.href='{% url 'surveys:survey_take' survey.id %}';return false;">
      </div>
    </form>
  </p>

{% endblock %}

surveys/templates/surveys/survey_take_perceptions.html
{% extends "base_bootstrap_nav_splash.html" %}
{% block content %}
{% load crispy_forms_tags %}
<p>
  <h1>{{ survey }}: Perceptions</h1>
  Instructions: For the student listed, read the statement and make a selection.
</p>
<p>
    <form action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for question, teammate, form in data %}
        <div class="border border-3 border-primary rounded-3 p-3 m-3">
            <h4>{{ teammate.name }}</h4>
            <h5><em>{{ question }}</em></h5>
            {{ form|crispy }}
        </div>
        {% endfor %}
      <div class= "p-3 m-3">
        <input class="btn btn-outline-primary" type="submit" value="Submit">
        <input class="btn btn-outline-warning" type="submit" value="Cancel" onclick="window.location.href='{% url 'surveys:survey_take' survey.id %}';return false;">
      </div>
    </form>
  </p>

{% endblock %}

surveys/templates/surveys/survey_take_qa.html
{% extends "base_bootstrap_nav_splash.html" %}
{% block content %}
{% load crispy_forms_tags %}
<p>
  <h1>{{ survey }}: Short Answer</h1>
  Instructions: Provide an answer for each question below. 280 character limit.
</p>
<p>
    <form action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for question, form in data %}
        <div class="border border-3 border-primary rounded-3 p-3 m-3">
            <h4>{{ question }}</h4>
            {{ form|crispy }}
        </div>
        {% endfor %}
      <div class= "p-3 m-3">
        <input class="btn btn-outline-primary" type="submit" value="Submit">
        <input class="btn btn-outline-warning" type="submit" value="Cancel" onclick="window.location.href='{% url 'surveys:survey_take' survey.id %}';return false;">
      </div>
    </form>
  </p>

{% endblock %}

surveys/templates/surveys/survey_take_topbot5.html
{% extends "base_bootstrap_nav_splash.html" %}
{% block content %}
{% load crispy_forms_tags %}
<p>
  <h1>{{ survey }}: Top 5 / Bottom 5</h1>
  Instructions: Select your Top 5 and Bottom 5 from the class. Order does not matter. You cannot select the same student twice in the same survey.
</p>
<p>
    <form action="" method="post">
        {% csrf_token %}
        {{ tf_formset.management_form }}
        <h3> Top 5 </h3>
        {% for form in tf_formset %}
        <div class="border border-3 border-primary rounded-3 p-3 m-3 w-25 d-inline-block">
            {{ form|crispy }}
        </div>
        {% endfor %}
      </br>
        {{ bf_formset.management_form }}
        <h3> Bottom 5 </h3>
        {% for form in bf_formset %}
        <div class="border border-3 border-danger rounded-3 p-3 m-3 w-25 d-inline-block">
            {{ form|crispy }}
        </div>
        {% endfor %}
      <div class= "p-3 m-3">
        <input class="btn btn-outline-primary" type="submit" value="Submit">
        <input class="btn btn-outline-warning" type="submit" value="Cancel" onclick="window.location.href='{% url 'surveys:survey_take' survey.id %}';return false;">
      </div>
    </form>
  </p>

{% endblock %}

surveys/templates/surveys/survey_view.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
    <h1>{{ survey.name }}</h1>

    <p>
        <h3>Nominations</h3>
        <ul class="list-group">
            {% for nom_q in survey.nomination_qs.all %}
            <li class="list-group-item">{{ nom_q }}</li>
            {% endfor %}
        </ul>
        <h3>Perceptions</h3>
        <ul class="list-group">
            {% for per_q in survey.perception_qs.all %}
            <li class="list-group-item">{{ per_q }}</li>
            {% endfor %}
        </ul>
        <h3>Q&As</h3>
        <ul class="list-group">
            {% for sur_q in survey.survey_qs.all %}
            <li class="list-group-item">{{ sur_q }}</li>
            {% endfor %}
        </ul>
        <h3>Peer Feedback: {{ survey.peer_feedback }}</h3>
        <h3>Top Five / Bottom Five: {{ survey.topbot5 }}</h3>
    </p>

{% endblock %}

surveys/templates/surveys/topbot5_search_results.html
<div id="searchresults" class="container">
    <div class="row justify-content-center">
        <div class="column col-5 border border-3 border-success p-3 m-3">
            <h2 class="sub-header">Top 5</h2>
            <table class="table table-hover">
                <tr>
                    <th>Student</th><th>Cohort</th><th>Source</th><th>Top 5s</th>
                </tr>
                {% for row in top5data %}
                <tr>
                    <td><a href={% url 'stucon:student_view' row.student.id %}>{{ row.student }}</a></td>
                    <td>{{ row.student.cohort }}</td>
                    <td>{{ row.student.source }}</td>
                    <td>{{ row.top5s }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="column col-5 border border-3 border-danger p-3 m-3">
            <h2 class="sub-header">Bottom 5</h2>
            <table class="table table-hover">
                <tr>
                    <th>Student</th><th>Cohort</th><th>Source</th><th>Bottom 5s</th>
                </tr>
                {% for row in bot5data %}
                <tr>
                    <td><a href={% url 'stucon:student_view' row.student.id %}>{{ row.student }}</a></td>
                    <td>{{ row.student.cohort }}</td>
                    <td>{{ row.student.source }}</td>
                    <td>{{ row.bot5s }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>