home/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "home"
urlpatterns = [
    path("", views.home_view, name="home_page"),
    path("unauthorized", views.unauthorized_view, name="unauthorized_view"),
    path("reset_password", views.reset_password, name="reset_password"),
]

rackandstack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rubric/", include("rubric.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("stucon/", include("stucon.urls")),
    path("gradebook/", include("gradebook.urls")),
    path("surveys/", include("surveys.urls")),
    path("", include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stucon/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "stucon"
urlpatterns = [
    path("", views.bulk_edit_list, name="student_list"),
    path("create", views.create_student_user, name="create_student_user"),
    path("<int:student_id>/edit", views.student_edit, name="student_edit"),
    path("<int:student_id>/", views.student_view, name="student_view"),
    path("<int:student_id>/delete", views.student_delete, name="student_delete"),
    path("bulk_create", views.bulk_create_students, name="bulk_create_students"),
    path("bulk_edit", views.bulk_edit_list, name="bulk_edit_list"),
    path("bulk_edit_results", views.bulk_edit_results, name="bulk_edit_results"),
    path(
        "bulk_status_update/<int:new_status>",
        views.bulk_status_update,
        name="bulk_status_update",
    ),
    path(
        "<int:student_id>/status_comment_view_checked",
        views.status_comment_view_checked,
        name="status_comment_view_checked",
    ),
    path(
        "<int:student_id>/status_comment_view_unchecked",
        views.status_comment_view_unchecked,
        name="status_comment_view_unchecked",
    ),
    path("csv_export", views.dump_csv_student_data, name="dump_student_data"),
    path("upload_image", views.upload_image, name="upload_image"),
    path(
        "<int:cohort>/student_directory",
        views.student_directory,
        name="student_directory",
    ),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

stucon/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Cohort(models.Model):
    name = models.CharField(max_length=100, unique=True, null=False)

    def __str__(self):
        return f"{self.name}"


class Team(models.Model):
    name = models.CharField(max_length=100, unique=True, null=False)

    def __str__(self):
        return f"{self.name}"


class Source(models.Model):
    name = models.CharField(max_length=30, unique=True, null=False)

    def __str__(self):
        return f"{self.name}"


class Student(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    cohort = models.ForeignKey(
        Cohort, null=True, blank=True, on_delete=models.DO_NOTHING
    )
    team = models.ForeignKey(Team, null=True, blank=True, on_delete=models.DO_NOTHING)
    candidate_number = models.CharField(
        max_length=10, null=False, unique=True
    )  # ex. "CN110" or "CN012" or DoDID number
    source = models.ForeignKey(
        Source, null=True, blank=True, on_delete=models.DO_NOTHING
    )

    class Status(models.TextChoices):
        ACTIVE = "act", "Active"
        DOR = "dor", "DOR"
        MEDDROP = "med", "Medical Drop"
        PERFDROP = "perf", "Performance Drop"

    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.ACTIVE, null=False
    )
    status_comment = models.CharField(max_length=240, null=True, blank=True, default="")
    image = models.ImageField(
        upload_to="images/", default="default_pic.png", null=False, blank=False
    )

    def __str__(self):
        return f"{self.user_id.last_name}, {self.user_id.first_name}"

    def name(self):
        return f"{self.user_id.last_name}, {self.user_id.first_name}"

    def username(self):
        return f"{self.user_id.username}"

stucon/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from stucon.models import Student, Cohort, Team

from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["source", "candidate_number", "cohort", "status"]


class StudentImageForm(ModelForm):
    class Meta:
        model = Student
        fields = ["image"]


class StatusForm(ModelForm):
    class Meta:
        model = Student
        fields = ["status"]


class NewStudentUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        ]

stucon/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
from django.http import QueryDict
from django.template.response import TemplateResponse
from django import template
import csv, io, copy

from .models import Student, Team, Cohort, Source
from .forms import NewStudentUserForm, StudentForm, StudentImageForm
from rubric.models import Trait
from gradebook.models import ObjectiveScore, TraitScore
from surveys.models import (
    TopFiveResponse,
    BottomFiveResponse,
    NominationResponse,
    PerceptionResponse,
)

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import user_passes_test

# Create your views here.
def course_admin_check(user):
    return user.groups.filter(name="course_admin").exists()


def student_check(user):
    return user.groups.filter(name="student").exists()


@user_passes_test(course_admin_check)
def create_student_user(request):
    if request.method == "POST":
        student_form = StudentForm(request.POST)
        if student_form.is_valid():
            new_user_form = NewStudentUserForm(request.POST)
            new_user = (
                new_user_form.save()
            )  # Create the User object from the form data.
            st_group = Group.objects.get(name="student")
            st_group.user_set.add(
                new_user
            )  # Add the newly created User to the student group
            st_cohort = Cohort.objects.get(
                pk=student_form["cohort"].value()
            )  # Find the Cohort for adding it to the new student object.
            st_source = Source.objects.get(
                pk=student_form["source"].value()
            )  # Find the Source
            new_student = Student(
                user_id=new_user,
                cohort=st_cohort,
                candidate_number=student_form["candidate_number"].value(),
                source=st_source,
            )
            new_student.save()  # Save the new student to the database.
            messages.add_message(
                request, messages.SUCCESS, f"Successfully created {new_student}."
            )
            return HttpResponseRedirect(reverse("stucon:student_list"))
        else:
            messages.add_message(request, messages.ERROR, student_form.errors)
            return HttpResponseRedirect(reverse("stucon:student_list"))

    user_form = NewStudentUserForm()
    student_form = StudentForm()
    return TemplateResponse(
        request,
        "stucon/student_form.html",
        {"user_form": user_form, "student_form": student_form},
    )


def validate_csv_student_data(csv_file):
    file_is_good = True
    issues = []
    data_set = csv_file.read().decode("UTF-8")
    io_string = io.StringIO(data_set)
    for row in csv.DictReader(io_string):
        candidate_num = row["CN"]
        if Student.objects.filter(candidate_number=candidate_num).exists():
            issues.append(f"Candidate Number already exists: {candidate_num}")
            file_is_good = False
        username = row["username"]
        if User.objects.filter(username=username).exists():
            issues.append(f"Username already exists: {username}")
            file_is_good = False
        source = row["source"]
        cohort = row["cohort"]
        password = row["password"]

        if not Source.objects.filter(name=source).exists():
            issues.append(f"Source does not exist: {source}")
            file_is_good = False
        if not Cohort.objects.filter(name=cohort).exists():
            issues.append(f"Cohort does not exist: {cohort}")
            file_is_good = False

        if len(password) < 8 or password == "12345678" or password == "password":
            issues.append(
                f"Password is: too short; or 12345678; or password. Not allowed."
            )
            file_is_good = False
    return file_is_good, issues


@user_passes_test(course_admin_check)
def bulk_create_students(request):
    if request.method == "GET":
        return TemplateResponse(request, "stucon/bulk_create_students.html", {})

    if request.method == "POST":
        csv_file = request.FILES["file"]
        csv_file_copy = copy.deepcopy(csv_file)

        if not csv_file.name.endswith(".csv"):
            messages.error(request, "This is not a CSV file.")
            return HttpResponseRedirect(reverse("stucon:bulk_create_students"))

        ## VALIDATE THE FILE IS CORRECTLY FORMATTED...
        file_is_good, issues = validate_csv_student_data(csv_file)
        if not file_is_good:
            return TemplateResponse(
                request,
                "stucon/bulk_create_students.html",
                {
                    "file_is_good": file_is_good,
                    "issues": issues,
                },
            )

        ## Open it up and start the import
        if save_csv_student_data(csv_file_copy):
            messages.add_message(
                request, messages.SUCCESS, "Successfully bulk imported users."
            )
        else:
            messages.add_message(request, messages.ERROR, "Issue importing new users.")
        return HttpResponseRedirect(reverse("stucon:bulk_create_students"))


def save_csv_student_data(csv_file):
    data_set = csv_file.read().decode("UTF-8")
    io_string = io.StringIO(data_set)
    for row in csv.DictReader(io_string):
        candidate_num = row["CN"]
        first_name = row["first_name"]
        last_name = row["last_name"]
        username = row["username"]
        password = row["password"]
        source = get_object_or_404(Source.objects.all(), name=row["source"])
        cohort = get_object_or_404(Cohort.objects.all(), name=row["cohort"])
        new_user = User.objects.create_user(
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        st_group = Group.objects.get(name="student")
        st_group.user_set.add(
            new_user
        )  # Add the newly created User to the student group

        new_student = Student.objects.create(
            user_id=new_user,
            candidate_number=candidate_num,
            cohort=cohort,
            source=source,
        )
        new_student.save()
    return True


@user_passes_test(course_admin_check)
def dump_csv_student_data(request):
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="student_data.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(
        ["CN", "first_name", "last_name", "username", "password", "source", "cohort"]
    )
    students = Student.objects.all()
    for student in students:
        writer.writerow(
            [
                str(student.candidate_number),
                student.user_id.first_name,
                student.user_id.last_name,
                student.username(),
                "hitthesurf",
                str(student.source),
                str(student.cohort),
            ]
        )

    return response


@user_passes_test(course_admin_check)
def student_list(request):
    students = Student.objects.all().order_by("candidate_number")
    paginator = Paginator(students, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return TemplateResponse(
        request,
        "stucon/student_list.html",
        {
            "page_obj": page_obj,
        },
    )


@user_passes_test(course_admin_check)
def student_edit(request, student_id):
    if request.method == "POST":
        stu = get_object_or_404(Student.objects.all(), pk=student_id)
        student_form = StudentForm(request.POST, instance=stu)
        user_form = NewStudentUserForm(request.POST, instance=stu.user_id)
        user_form.save()
        student_form.save()
        messages.add_message(
            request, messages.SUCCESS, f"Successfully updated { stu }."
        )
        return HttpResponseRedirect(reverse("stucon:student_list"))

    student = get_object_or_404(Student.objects.all(), pk=student_id)
    student_form = StudentForm(instance=student)
    user_form = NewStudentUserForm(instance=student.user_id)

    return TemplateResponse(
        request,
        "stucon/student_form.html",
        {
            "student_form": student_form,
            "user_form": user_form,
            "student": student,
        },
    )


def get_average_traitscore(student_id, trait_id):
    stu = get_object_or_404(Student.objects.all(), pk=student_id)
    tscores = TraitScore.objects.filter(student=student_id, trait=trait_id)
    sum = 0
    count = 0
    for tscore in tscores:
        sum = sum + tscore.score
        count = count + 1
    if count == 0:
        return ("--", count)
    return (round(sum / count, 2), count)


def get_perceptions_avgs(student_id):
    student = get_object_or_404(Student.objects.all(), pk=student_id)
    perceptions = PerceptionResponse.objects.filter(subject=student)
    self_perception = "---"
    others_perception = "---"
    if perceptions.exists():
        self_perception_total = 0
        self_perception_count = 0
        others_perception_total = 0
        others_perception_count = 0
        for perception in perceptions:
            if perception.author == student:
                self_perception_total += perception.score
                self_perception_count += 1
            else:
                others_perception_total += perception.score
                others_perception_count += 1

        if self_perception_count == 0:
            self_perception = "---"
        else:
            self_perception = round(self_perception_total / self_perception_count, 2)

        if others_perception_count == 0:

stucon/templates/stucon/bulk_create_students.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
{% load crispy_forms_tags %}
<h1>Create Students from CSV</h1>
<p>
    {% if issues %}
    The file was not uploaded due to the following issues:
    <ul>
    {% for issue in issues %}
        <li>{{ issue }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <p>
        The first line of the CSV file will be read as headers. Use the following as the first line in your CSV file to insure you have the proper format:
        <pre class="border border-2 bg-dark text-white m-3 p-3"><code>CN,first_name,last_name,username,password,source,cohort</code></pre>
    </p>
    <p>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="file1"> Upload a file</label>
            <input class="form-control" type="file" id="file1" name="file">
            <small>Only accepts CSV files</small>
            </br>
            <input class="btn m-3 btn-outline-primary" type="submit" value="Submit">
        </form>
    </p>
  </p>

{% endblock %}

stucon/templates/stucon/bulk_edit_list.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
    <h1>Manage Students</h1>
    <p>
        <div>
            <a class="btn btn-outline-primary" href="{% url 'stucon:create_student_user' %}">Create Student</a>
            <a class="btn btn-outline-primary" href="{% url 'stucon:bulk_create_students' %}">Bulk CSV Upload</a>
            <a class="btn btn-outline-primary" href="{% url 'stucon:dump_student_data' %}">CSV Data Export</a>
        </div>
    </br>
        <form
        hx-get="{% url 'stucon:bulk_edit_results' %}"
        hx-target="#bulk-results"
        hx-swap="outerHTML"
        hx-trigger="submit, input delay:0.3s"
        >
            <div class="container">
                <div class="row">
                    <div class="column col-3">
                        Search:
                        <input type="text" class="form-control" name="search" placeholder="Filter..." value="{{ search }}">
                    </div>
                    <div class="column col-3">
                        Status:
                        <select class="form-control" name="status" id="status">
                            <option value="all">All</option>
                            <option value="act">Active</option>
                            <option value="dor">DOR</option>
                            <option value="perf">Perf Drop</option>
                            <option value="med">Med Drop</option>
                        </select>
                    </div>
                    <div class="column col-3">
                        Sort by:
                        <select class="form-control" name="sortby" id="sortby">
                            <option value="name">Name</option>
                            <option value="cn">Candidate Number</option>
                            <option value="source">Source</option>
                            <option value="cohort">Cohort</option>
                        </select>
                    </div>
                </div>
            </div>            
        </form>
    </br>
    <div hx-include="#bulk-update" hx-target="#bulk-results">
        Status Actions:
        <a class="btn btn-outline-success" hx-post="{% url 'stucon:bulk_status_update' 0 %}">Active</a>
        <a class="btn btn-outline-danger" hx-post="{% url 'stucon:bulk_status_update' 1 %}">DOR</a>
        <a class="btn btn-outline-danger" hx-post="{% url 'stucon:bulk_status_update' 2 %}">Perf Drop</a>
        <a class="btn btn-outline-danger" hx-post="{% url 'stucon:bulk_status_update' 3 %}">Med Drop</a>
    </div>
    </br>
        {% include 'stucon/bulk_edit_results.html' %}
    </p>
    

{% endblock %}

stucon/templates/stucon/bulk_edit_results.html
<div id="bulk-results">
    <form id="bulk-update">
        <table class="table">
            <thead>
                <tr>
                    <th></th><th>Candidate #</th> <th>Name</th><th>Cohort</th><th>Source</th><th>Status</th><th>Notes</th><th></th><th></th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr>
                        <td><input 
                            hx-target="closest tr"
                            hx-swap="outerHTML"
                            hx-get="{% url 'stucon:status_comment_view_checked' student.id %}"
                            type="checkbox"
                            name="ids"
                            value="{{ student.id }}"
                            >
                        </td>
                        <td><a href="{% url 'stucon:student_view' student.id %}"> {{ student.candidate_number }} </a></td>
                        <td>{{ student.name }}</td>
                        <td>{{ student.cohort }}</td>
                        <td>{{ student.source }}</td>
                        <td>{{ student.status }}</td>
                        <td>
                            <small>{{ student.status_comment }}</small>
                        </td>
                        <td><a href="{% url 'stucon:student_edit' student.id %}"> Edit </a></td>
                        <td><a href="{% url 'stucon:student_delete' student.id %}"> Delete </a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>

stucon/templates/stucon/image_upload.html
{% extends "base_bootstrap_nav_splash.html" %}
{% block content %}
{% load crispy_forms_tags %}
<h1>Upload a picture:</h1>
<p>
    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ image_form|crispy }}
    </br>
      <input class="btn btn-outline-primary" type="submit" value="Submit">
      <input class="btn btn-outline-warning" type="submit" value="Cancel" onclick="window.location.href='{% url 'home:home_page' %}';return false;">
    </form>
  </p>

{% endblock %}

stucon/templates/stucon/status_comment_form_checked.html
<tr>
    <td><input 
        hx-target="closest tr"
        hx-swap="outerHTML"
        hx-get="{% url 'stucon:status_comment_view_unchecked' student.id %}"
        type="checkbox"
        name="ids"
        value="{{ student.id }}"
        checked
        >
    </td>
    <td><a href="{% url 'stucon:student_view' student.id %}"> {{ student.candidate_number }} </a></td>
    <td>{{ student.name }}</td>
    <td>{{ student.cohort }}</td>
    <td>{{ student.source }}</td>
    <td>{{ student.status }}</td>
    <td>
        <input type='text' name='comment' value='{{ student.status_comment }}'>
    </td>
    <td><a href="{% url 'stucon:student_edit' student.id %}"> Edit </a></td>
    <td><a href="{% url 'stucon:student_delete' student.id %}"> Delete </a></td>
</tr>

stucon/templates/stucon/status_comment_form_unchecked.html
<tr>
    <td><input 
        hx-target="closest tr"
        hx-swap="outerHTML"
        hx-get="{% url 'stucon:status_comment_view_checked' student.id %}"
        type="checkbox"
        name="ids"
        value="{{ student.id }}"
        >
    </td>
    <td><a href="{% url 'stucon:student_view' student.id %}"> {{ student.candidate_number }} </a></td>
    <td>{{ student.name }}</td>
    <td>{{ student.cohort }}</td>
    <td>{{ student.source }}</td>
    <td>{{ student.status }}</td>
    <td>
        {{ student.status_comment }}
        <!--<input type='text' name='comment' value='{{ student.status_comment }}'> -->
    </td>
    <td><a href="{% url 'stucon:student_edit' student.id %}"> Edit </a></td>
    <td><a href="{% url 'stucon:student_delete' student.id %}"> Delete </a></td>
</tr>

stucon/templates/stucon/student_delete.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
<h1>Delete Student</h1>

<p>Are you sure you want to delete this student: {{ student.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-outline-danger" type="submit" value="Yes, delete.">
</form>
{% endblock %}

stucon/templates/stucon/student_directory.html
{% extends "base_bootstrap_nav_splash.html" %}
{% block content %}
    <h1>Student Directory</h1>
    <h3>{{ cohort }}</h3>
    <p>
        {% for student in student_list %}
        <p class="clearfix">
        {{ student.name }} <img src={{ student.image.url }} class="img-fluid img-thumbnail float-start" width="200em">
        </p>
        {% endfor %}
    </p>

{% endblock %}

stucon/templates/stucon/student_form.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% if student %}
    <h1>Edit Student</h1>
{% else %}
    <h1>Create Student</h1>
{% endif %}
<p>
    <form action="" method="post">
      {% csrf_token %}
      {{ user_form|crispy }}
      {{ student_form|crispy }}
    </br>
      <input class="btn btn-outline-primary" type="submit" value="Submit">
      <input class="btn btn-outline-warning" type="submit" value="Cancel" onclick="window.location.href='{% url 'stucon:student_list' %}';return false;">
      {% if student %}
      <input class="btn btn-outline-danger" type="submit" value="Delete" onclick="window.location.href='{% url 'stucon:student_delete' student.id %}'; return false;">
      {% endif %}
    </form>
  </p>

{% endblock %}

stucon/templates/stucon/student_list.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
    <h1>Students</h1>
    <p>
        <a class="btn btn-outline-primary" href="{% url 'stucon:create_student_user' %}">Create Student</a>
        <a class="btn btn-outline-primary" href="{% url 'stucon:bulk_edit_list' %}">Manage Students</a>
    {% if page_obj %}
    <table class="table">
        <thead>
            <tr>
                <th> Candidate # </th> <th>Name</th><th>Cohort</th><th>Source</th><th> </th> <th> </th>
            </tr>
        </thead>
        <tbody>
            {% for student in page_obj.object_list %}
            <tr>
                <td><a href="{% url 'stucon:student_view' student.id %}"> {{ student.candidate_number }} </a></td>
                <td>{{ student.name }}</td>
                <td>{{ student.cohort }}</td>
                <td>{{ student.source }}</td> 
                <td><a href="{% url 'stucon:student_edit' student.id %}"> Edit </a></td>
                <td><a href="{% url 'stucon:student_delete' student.id %}"> Delete </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
    <p>There are no students in the database.</p>
    {% endif %}
    </p>

{% endblock %}

stucon/templates/stucon/student_view.html
{% extends "base_bootstrap_nav.html" %}
{% block content %}
<div>
    <img src={{ student.image.url }} class="img-fluid img-thumbnail float-start" width="300em">
    <h1>{{ student.name }} | {{ student.candidate_number }}</h1>
    <p>
        Source: {{ student.source }} </br>
        Cohort: {{ student.cohort }} </br>
        {% if student.team %}
        Team: {{ student.team }}
        {% endif %}
    </p>
</div>
    <p class="clearfix">
        <h3>Trait Summary</h3>
        <ul class="list-group">
            {% for trait_name, trait_avg in trait_averages.items %}
            <li class="list-group-item">{{ trait_name }}: {{ trait_avg.0 }} <small>({{ trait_avg.1 }} data points)</small></li>
            {% endfor %}
        </ul>
    </p>
    <p>
        <h3>Peer Evaluations Summary</h3>
        <ul class="list-group">
            <li class="list-group-item">Positive Nominations: {{ pos_noms }}</li>
            <li class="list-group-item">Negative Nominations: {{ neg_noms }}</li>
            <li class="list-group-item">Top Fives: {{ topfive_count }}</li>
            <li class="list-group-item">Bottom Fives: {{ botfive_count }}</li>
            {% if self_perceptions %}
            <li class="list-group-item">Self Perception: {{ self_perceptions }} / 4.00</li>
            {% endif %}
            {% if others_perceptions != None %}
            <li class="list-group-item">Others Perception: {{ others_perceptions }} / 4.00</li>
            {% endif %}
            <li class="list-group-item"><a href="#">Comments...</a></li>
    </p>

{% endblock %}