gradebook/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='gradebook'
urlpatterns = [
    path('', views.gradebook_menu, name='gradebook_menu'),
    path('select_evo/', views.gradebook_selection, name='gradebook_selection'),
    path('grade_evo_list/<int:cohort_id>/<int:evolution_id>', views.grade_evo_list, name='grade_evo_list'),
    path('grade_evo/<int:student_id>/<int:evolution_id>', views.grade_evo, name='grade_evo'),
    path('grade_evo/<int:student_id>/<int:evolution_id>/delete', views.grade_evo_delete, name='grade_evo_delete'),
    path('csv_dump', views.gradebook_csv_dump, name='gradebook_csv_dump'),
]

home/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "home"
urlpatterns = [
    path("", views.home_view, name="home_page"),
    path("unauthorized", views.unauthorized_view, name="unauthorized_view"),
    path("reset_password", views.reset_password, name="reset_password"),
]

rackandstack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rubric/", include("rubric.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("stucon/", include("stucon.urls")),
    path("gradebook/", include("gradebook.urls")),
    path("surveys/", include("surveys.urls")),
    path("", include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rubric/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='rubric'
urlpatterns = [
    path('evolutions/', views.evolution_list, name='evolution_list'),
    path('evolutions/create/', views.evolution_create, name='evolution_create'),
    path('evolutions/create_obj/', views.obj_evolution_create, name='obj_evolution_create'),
    path('evolutions/<int:evolution_id>/', views.evolution_detail, name='evolution_detail'),
    path('evolutions/<int:evolution_id>/edit', views.evolution_edit, name='evolution_edit'),
    path('evolutions/<int:evolution_id>/delete', views.evolution_delete, name='evolution_delete'),
    path('evolutions/csv_dump', views.evolution_csv_dump, name='evolution_csv_dump'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

stucon/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "stucon"
urlpatterns = [
    path("", views.bulk_edit_list, name="student_list"),
    path("create", views.create_student_user, name="create_student_user"),
    path("<int:student_id>/edit", views.student_edit, name="student_edit"),
    path("<int:student_id>/", views.student_view, name="student_view"),
    path("<int:student_id>/delete", views.student_delete, name="student_delete"),
    path("bulk_create", views.bulk_create_students, name="bulk_create_students"),
    path("bulk_edit", views.bulk_edit_list, name="bulk_edit_list"),
    path("bulk_edit_results", views.bulk_edit_results, name="bulk_edit_results"),
    path(
        "bulk_status_update/<int:new_status>",
        views.bulk_status_update,
        name="bulk_status_update",
    ),
    path(
        "<int:student_id>/status_comment_view_checked",
        views.status_comment_view_checked,
        name="status_comment_view_checked",
    ),
    path(
        "<int:student_id>/status_comment_view_unchecked",
        views.status_comment_view_unchecked,
        name="status_comment_view_unchecked",
    ),
    path("csv_export", views.dump_csv_student_data, name="dump_student_data"),
    path("upload_image", views.upload_image, name="upload_image"),
    path(
        "<int:cohort>/student_directory",
        views.student_directory,
        name="student_directory",
    ),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

surveys/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'surveys'
urlpatterns = [
    path('', views.survey_list, name='survey_list'),
    path('create', views.survey_create, name='survey_create'),
    path('<int:survey_id>/edit', views.survey_edit, name='survey_edit'),
    path('<int:survey_id>/', views.survey_view, name='survey_view'),
    path('<int:survey_id>/delete', views.survey_delete, name='survey_delete'),
    path('take/<int:survey_id>', views.survey_take_menu, name='survey_take'),
    path('take/<int:survey_id>/nominations',
         views.survey_take_nominations, name='survey_take_nominations'),
    path('take/<int:survey_id>/perceptions',
         views.survey_take_perceptions, name='survey_take_perceptions'),
    path('take/<int:survey_id>/peerfeedback',
         views.survey_take_pf, name='survey_take_pf'),
    path('take/<int:survey_id>/questions',
         views.survey_take_qa, name='survey_take_qa'),
    path('take/<int:survey_id>/topbot5',
         views.survey_take_topbot5, name='survey_take_topbot5'),
    path('review', views.survey_review_menu, name='survey_review_menu'),
    path('review/nominations', views.survey_review_nominations,
         name='survey_review_nominations'),
    path('review/nom/search', views.nom_search_view, name='nom_search_view'),
    path('review/qa/search', views.qa_search_view, name='qa_search_view'),
    path('review/topbot5/search', views.topbot5_search_view,
         name='topbot5_search_view'),
    path('review/questions', views.survey_review_questions,
         name='survey_review_questions'),
    path('review/topbot5', views.survey_review_topbot5,
         name='survey_review_topbot5'),
    path('export/survey_question_responses', views.dump_csv_survey_question_data,
         name='export_survey_question_responses'),
    path('export/survey_nomination_responses', views.dump_csv_survey_nomination_data,
         name='export_survey_nomination_responses'),
    path('export/survey_topbot5_responses', views.dump_csv_survey_topbot5_data,
         name='export_survey_topbot5_responses'),
    path('export/survey_pf_responses', views.dump_csv_survey_pf_data,
         name='export_survey_pf_responses'),
    path('export/survey_perception_responses', views.dump_csv_survey_perception_data,
         name='export_survey_perception_responses'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
        
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<meta name="rackandstack_version" content="2021-12-08">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %}
{% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{ msg.message }}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
    <script type="text/javascript" src="{% static 'js/htmx.min.js' %}"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
      </script>
</body>
</html>

templates/base_bootstrap_nav.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><h1>psb</h1></a>
      <button class="navbar-light navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            {% url 'home:home_page' as home %}
            <a class="nav-link {% if request.get_full_path == home %} active {% endif %}" href="{% url 'home:home_page' %}">Home</a>
          </li>
          <li class="nav-item">
            {% url 'rubric:evolution_list' as evo %}
            <a class="nav-link {% if request.get_full_path == evo %} active {% endif %}" aria-current="page" href="{% url 'rubric:evolution_list' %}">Evolutions</a>
          </li>
          <li class="nav-item">
            {% url 'stucon:student_list' as xyz %}
            <a class="nav-link {% if request.get_full_path == xyz %} active {% endif %}" aria-current="page" href="{% url 'stucon:student_list' %}">STUCON</a>
          </li>
          <li class="nav-item">
            {% url 'gradebook:gradebook_menu' as gdb %}
            <a class="nav-link {% if request.get_full_path == gdb %} active {% endif %}" aria-current="page" href="{% url 'gradebook:gradebook_menu' %}">Gradebook</a>
          </li>
          <li class="nav-item">
            {% url 'surveys:survey_list' as sur %}
            <a class="nav-link {% if request.get_full_path == sur %} active {% endif %}" aria-current="page" href="{% url 'surveys:survey_list' %}">Surveys</a>
          </li>
        </ul>

        <ul class="navbar navbar-primary navbar-right">
            {% if user.is_authenticated %}
          <li class="nav-item dropdown nav">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_superuser %}
              <li><a class="dropdown-item" href="/admin/">Admin Menu</a></li>
              <li><hr class="dropdown-divider"></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'home:reset_password' %}">Change Password</a></li>
              <li><a class="dropdown-item" href="/accounts/logout/">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item nav"><a class="btn btn-primary" href="/accounts/login/" role="button">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% endblock %}

templates/base_bootstrap_nav_splash.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><img src="/media/rackstack_banner.png" class="img-fluid float-start" width="130em"></a>
      <button class="navbar-light navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            {% url 'home:home_page' as home %}
            <a class="nav-link {% if request.get_full_path == home %} active {% endif %}" href="{% url 'home:home_page' %}">Home</a>
          </li>
        </ul>

        <ul class="navbar navbar-primary navbar-right">
            {% if user.is_authenticated %}
          <li class="nav-item dropdown nav">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_superuser %}
              <li><a class="dropdown-item" href="/admin/">Admin Menu</a></li>
              <li><hr class="dropdown-divider"></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'home:reset_password' %}">Change Password</a></li>
              <li><a class="dropdown-item" href="/accounts/logout/">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item nav"><a class="btn btn-primary" href="/accounts/login/" role="button">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% endblock %}